### ISSUE TITLE
[Badges] Load from filesystem

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#124]
#### Current Behavior
Site images are hard-coded into this single-page site (https://badges.layer5.io/).

#### Desired Behavior
Change into a collection of badges that are dynamically retrieved from filesystem. 

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by gopivaibhav** [comment]
As discussed in slack, I am going to take this up @leecalcote
