### ISSUE TITLE
[Recognition Program] Use of Qantas Soft font

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#134]
#### Current Behavior
The Layer5 brand font of Qanelas Soft is not being properly referenced on https://badges.layer5.io

#### Desired Behavior
Pervasive use of Qanelas Soft font. San serif as the backup font family.

#### Implementation
Ensure that fonts.css is in the right folder and is being imported successfully.

#### Acceptance Tests
1. All font is in Qanelas Soft with sans serif as the secondary font.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@gopivaibhav fyi...

**Comment by gopivaibhav** [comment]
Can I work on this issue? @leecalcote 
Or should I review when someone made the PR?

**Comment by leecalcote** [comment]
@gopivaibhav let's get you rolling on it. 👍
