### ISSUE TITLE
Adding a new section with Certifications

### ISSUE THREAD

**Issue by gopivaibhav** [layer5labs/meshery-extensions-packages#139]
#### Current Behavior

No section available for certifications

#### Desired Behavior

Link for Reference of what to do- https://meshery.io/catalog 

#### Implementation

New section with certifications having a [coming soon](https://layer5.io/static/coming-soon-3e7a0d282ee94e816f417bb249c3adb0.webp) sign

#### Acceptance Tests

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
I tossed in an update... you might find opportunity to improve it. 

I keep stepping on your toes here accidentally, because we want to announce this pronto.

**Comment by gopivaibhav** [comment]
Thankyou, I was in touch with @ritiksaxena124 regarding this to make a new card for certifications

**Comment by gopivaibhav** [comment]
Completed with this [PR](https://github.com/layer5labs/meshery-extensions-packages/pull/144)
