### ISSUE TITLE
Add Recognition Program logo

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#141]
#### Desired Behavior
Identify a spot to display this logo as an image representing the program itself.

#### Mockups
![Recognition Program](https://github.com/layer5labs/meshery-extensions-packages/assets/7570704/d051b75e-967c-41db-9483-5619adc7cc38)

This SVG might need to be converted to PNG to ensure Qanelas Soft font remains intact.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
@ritiksaxena124 do you might dropping a PNG version of this logo here?

**Comment by gopivaibhav** [comment]
Thank Lee, I am about to create this issue and it was already made

**Comment by ritiksaxena124** [comment]
Here is PNG @gopivaibhav that you can use

![asset](https://github.com/layer5labs/meshery-extensions-packages/assets/51539117/299d3bff-416f-4508-bb0e-29050c54c91b)
