### ISSUE TITLE
Add Code Snippet as an example of embedding badge in Github Profile

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#145]

**Comment by fiifidawson** [comment]
@leecalcote can I work on this?

**Comment by gopivaibhav** [comment]
Am I supposed to add an example of markdown code in the GitHub section? // @leecalcote 
Something like this- 
`<a href= "https://meshery.layer5.io/user/<USER_ID>?tab=badges"><img width="130px" height="200px" src = "https://badges.layer5.io/assets/badges/<BADGE_NAME>" alt = "Layer5 Badge" /></a >`
