### ISSUE TITLE
Make the Project Badges dynamic

### ISSUE THREAD

**Issue by gopivaibhav** [layer5labs/meshery-extensions-packages#150]
#### Current Behavior

Currently, the achievement badges are made dynamic but not project badges

#### Desired Behavior

We need them to be dynamic as well

#### Implementation

Add the project badges information to the [JSON](https://github.com/layer5labs/meshery-extensions-packages/blob/master/site/src/badgesInfo.json) file by cross-checking from [this file](https://github.com/layer5labs/meshery-extensions-packages/blob/master/site/src/sitecomponents/BadgeGrid/index.js#L24) 

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Nithinyanamaddi** [comment]
I would like to work on this.

**Comment by gopivaibhav** [comment]
Sure, Here you go!!

**Comment by Khemendra-Bhardwaj** [comment]
Can I work on this one ?

**Comment by gopivaibhav** [comment]
Hey @Khemendra-Bhardwaj it was already to @Nithinyanamaddi and if he fails to do a PR within next 3 days, then I will assign this to you
