### ISSUE TITLE
[UI] Update the Github profiles section

### ISSUE THREAD

**Issue by gopivaibhav** [layer5labs/meshery-extensions-packages#160]
#### Current Behavior

![image](https://github.com/layer5labs/meshery-extensions-packages/assets/78922463/7023adb9-811b-47d8-bb6f-e4e3415616bf)

#### Desired Behavior

![image](https://github.com/layer5labs/meshery-extensions-packages/assets/78922463/350e37e2-f1d8-40fc-970a-977a7f305af0)

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue. Please assign me.
