### ISSUE TITLE
[CI] Make sure that UI build doesn't cache

### ISSUE THREAD

**Issue by gopivaibhav** [layer5labs/meshery-extensions-packages#161]
#### Current Behavior

Currently, we are facing a problem with the cache when building UI through GitHub workflow. (Not every time though)

#### Desired Behavior

Update the workflow so that we don't face any trouble with the cache issues in the later releases.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by VaibhavMalik4187** [comment]
> 

Could you please provide some additional context and maybe some URLs of the workflow failures?

**Comment by gopivaibhav** [comment]
@leecalcote I guess there is no such cache issue now as @theBeginner86 [mentioned](https://layer5io.slack.com/archives/G019GNQGPL4/p1693434116869119?thread_ts=1693428983.258089&cid=G019GNQGPL4)  that he is missing a key which is causing the trouble in prod. So, Can I close this issue?

**Comment by leecalcote** [comment]
Oh, very good. I'm unaware of the details, so, yes, if @theBeginner86 is canceling this request...

Thanks, guys.
