### ISSUE TITLE
Add Google Tag Manager script to badges site

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#175]
#### Current Behavior
We have no visibility into the demographics of site visitors.

#### Desired Behavior
1. Collect analytics based on site visitors into GTM.
1. _Future: Track event: users clicking on copy-to-clipboard button for copying markdown to display badge on their profiles.

#### Implementation

1. Paste this code as high in the `<head>` of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PDTVCLXM');</script>
<!-- End Google Tag Manager -->
```

2. Paste this code immediately after the opening <body> tag:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PDTVCLXM"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

#### Acceptance Tests
1. Telemetry from site visitors begins showing up in GTM badges.layer5.io account.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by akhilender-bongirwar** [comment]
@leecalcote, I would like to solve this issue

**Comment by StillAbeginnerr** [comment]
@leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
Thanks, all. 👍 Mission accomplished.
