### ISSUE TITLE
Post Review Rockstar badge

### ISSUE THREAD

**Issue by hamza-mohd** [layer5labs/meshery-extensions-packages#197]
#### Current Behavior
A new badge is available - https://discuss.layer5.io/t/visual-design-draft-badge-for-review-rockstar/3948

#### Desired Behavior
Badge should be displayed on this site.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Chenwei-Niu** [comment]
Hi, I'd like to work on this. Can you please assign this issue to me.

**Comment by hamza-mohd** [comment]
Oh! I missed your message, @Chenwei-Niu! Oh, no. I'm sorry about that.

**Comment by hamza-mohd** [comment]
@ritiksaxena124 is there another badge that @Chenwei-Niu might design?

**Comment by ritiksaxena124** [comment]
Thanks for your contribution 🙌. We appreciate your efforts 🚀. 

we are closing this issue as this is already completed.
