### ISSUE TITLE
The "View leaderboard" button doesn't direct to leaderboard instead it directs to slack channel

### ISSUE THREAD

**Issue by Raj100679** [layer5labs/meshery-extensions-packages#229]
#### Current Behavior

The "View leaderboard" button in https://badges.layer5.io/ doesn't directs to leaderboard instead it directs to slack channel

#### Screenshots/Logs

https://github.com/layer5labs/meshery-extensions-packages/assets/85561967/9ffd674f-29e7-4b67-a340-6d5161a18237

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Raj100679** [comment]
Can you check this if it is valid and assign me

**Comment by ritiksaxena124** [comment]
Thanks for raising this @Raj100679. redirect the user to https://discuss.layer5.io/u?order=likes_received

**Comment by Raj100679** [comment]
@ritiksaxena124 "Community Leaderboard" link is also broken in footer, which link should I replace it with
