### ISSUE TITLE
Catalog: limit overview page to 9 cards

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#251]
<@U05MK682475> a request of you, if you have time… the <http://Meshery.io|Meshery.io> Catalog loads too many designs onto a page, causing it to fail much of the time, because it is heavy on loading remote images. - <https://meshery.io/catalog>

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1711474802183339?thread_ts=1711474802.183339&cid=C015QJKUMPU)

**Comment by abhishekmmgn** [comment]
I found similar issue https://github.com/meshery/meshery.io/issues/1656.

Before: 
![image](https://github.com/layer5labs/meshery-extensions-packages/assets/107319349/c7523824-befb-414c-b8f2-9d7847c94a41)


Now: 
![image](https://github.com/layer5labs/meshery-extensions-packages/assets/107319349/0cb9b6fe-f6ea-4d7d-aeea-540f137de8f5)

Also, I think 12 would be better as we have 1, 2 and 3 columns grid. And even if we plan to add 4, 12 is a safe choice.

Should I raise an PR?

**Comment by abhishekmmgn** [comment]
This issue has been raised previously https://github.com/meshery/meshery.io/issues/1656

Now, they planned for 10 cards. This is what it looks like on 12 cards.
We have 1, 2 and 3 columns grid and math favors the 12. Also, if we go for 4 cols in the future, it will work.

Kindly let me know, if I should keep 9 like you told me to.

https://github.com/layer5labs/meshery-extensions-packages/assets/107319349/709e7ea1-3b72-4b9a-839e-431b94ccc4e3

**Comment by vishalvivekm** [comment]
Thank you @abhishekmmgn
