### ISSUE TITLE
[Docs] Include Meshery Embed component in readme.md

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#270]
#### Current State
A high-level listing of https://github.com/layer5labs/meshery-extensions-packages/tree/master/meshery-design-embed#meshery-design-embed-package is missing in the repo's readme.

#### Desired State

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aviral0702** [comment]
Can I work on this issue ?

**Comment by leecalcote** [comment]
Thanks, @Aviral0702
