### ISSUE TITLE
Hydra in the Meshery Cloud

### ISSUE THREAD

**Issue by legendarykamal** [layer5labs/meshery-extensions-packages#30]
**Description**

Hydra is the OIDC provider we use in meshery cloud but it is not helpful for users.

![Screenshot from 2022-08-16 22-16-07](https://user-images.githubusercontent.com/95926324/185113969-3356f132-2d3f-4d2b-9391-2af90ad4106d.png)

**Expected Behavior**

An alternative to it could be found.

**Environment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
[Optional] **To Reproduce**
1. Go to 'provider-ui'
2. Click on 'login'

**Comment by Abhishek-kumar09** [comment]
There has been several reasons to it:
There may have any number of false clicks during login that may trigger this, or, Its been the problem with the incorrect "BUILD" variable setup during server start(only when someone logs in by building the server locally). 

For second cause, the contributor needs to have upstream setup for `meshery/meshery`
