### ISSUE TITLE
[CI] Use Cloud Prod as Provider for Kanvas rollouts

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#322]
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
completed
