### ISSUE TITLE
[CI] Enhance Test Result Formatting

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#341]
#### Current Behavior
See https://github.com/layer5labs/meshery-extensions/pull/2918#issuecomment-2386485514

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
@jerensl how'd we make out here?

**Comment by jerensl** [comment]
> @jerensl how'd we make out here?

that's happened because of the text comes close to the table and lose the format, so I add some text after the table in the format to separate them

**Comment by l5io** [comment]
Makes much sense. What do you think? Ready to close this one out?

**Comment by leecalcote** [comment]
Makes much sense. What do you think? Ready to close this one out?
