### ISSUE TITLE
Failure in "Publish Assets" workflow

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#7]
**Description**
<img width="1553" alt="Screen Shot 2021-06-13 at 9 32 49 PM" src="https://user-images.githubusercontent.com/7570704/121832131-f606df80-cc8e-11eb-9808-d39e34120251.png">

@kumarabd when closing this issue, please document the root cause and how the issue was resolved.

**Comment by leecalcote** [comment]
Have you identified the issue in this workflow, @kumarabd?

**Comment by kumarabd** [comment]
This happened due to the package(from meshery extensions) not being available for download, Ive disabled this flow and changed Meshery-extensions to publish directly to this repository.
